[2024-05-11 23:26:25,000][flwr][INFO] - Starting Flower simulation, config: num_rounds=1, no round_timeout
[2024-05-11 23:26:52,477][flwr][INFO] - Flower VCE: Ray initialized with resources: {'CPU': 40.0, 'node:__internal_head__': 1.0, 'object_store_memory': 92461962854.0, 'accelerator_type:V100': 1.0, 'GPU': 1.0, 'node:10.53.222.24': 1.0, 'memory': 205744579994.0}
[2024-05-11 23:26:52,479][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2024-05-11 23:26:52,481][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 2, 'num_gpus': 1.0}
[2024-05-11 23:26:52,496][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 1 actors
[2024-05-11 23:26:52,502][flwr][INFO] - [INIT]
[2024-05-11 23:26:52,504][flwr][INFO] - Requesting initial parameters from one random client
[2024-05-11 23:27:46,387][flwr][INFO] - Received initial parameters from one random client
[2024-05-11 23:27:46,389][flwr][INFO] - Evaluating initial global parameters
[2024-05-11 23:27:46,788][flwr][INFO] - initial parameters (loss, other metrics): 0.0, {}
[2024-05-11 23:27:46,790][flwr][INFO] - 
[2024-05-11 23:27:46,792][flwr][INFO] - [ROUND 1]
[2024-05-11 23:27:46,794][flwr][INFO] - configure_fit: strategy sampled 2 clients (out of 2)
[2024-05-11 23:28:27,969][flwr][ERROR] - Traceback (most recent call last):
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1831058, ip=10.53.222.24, actor_id=3248fa26c35499a58d6bf00101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2e5a5bffa0>)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/scratch/nshaheen/project/may_federated/LLaVA_flowertune/client.py", line 84, in fit
    results = trainer.train()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 1638, in _inner_training_loop
    self.create_optimizer_and_scheduler(num_training_steps=max_steps)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 916, in create_optimizer_and_scheduler
    self.create_scheduler(num_training_steps=num_training_steps, optimizer=optimizer)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 1118, in create_scheduler
    self.lr_scheduler = get_scheduler(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/optimization.py", line 388, in get_scheduler
    return schedule_func(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/optimization.py", line 174, in get_cosine_schedule_with_warmup
    return LambdaLR(optimizer, lr_lambda, last_epoch)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 217, in __init__
    super().__init__(optimizer, last_epoch, verbose)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 78, in __init__
    self._initial_step()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 84, in _initial_step
    self.step()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 147, in step
    values = self.get_lr()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 264, in get_lr
    return [base_lr * lmbda(self.last_epoch)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 264, in <listcomp>
    return [base_lr * lmbda(self.last_epoch)
TypeError: can't multiply sequence by non-int of type 'float'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1831058, ip=10.53.222.24, actor_id=3248fa26c35499a58d6bf00101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2e5a5bffa0>)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: can't multiply sequence by non-int of type 'float'

[2024-05-11 23:28:27,972][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1831058, ip=10.53.222.24, actor_id=3248fa26c35499a58d6bf00101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2e5a5bffa0>)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/scratch/nshaheen/project/may_federated/LLaVA_flowertune/client.py", line 84, in fit
    results = trainer.train()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 1638, in _inner_training_loop
    self.create_optimizer_and_scheduler(num_training_steps=max_steps)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 916, in create_optimizer_and_scheduler
    self.create_scheduler(num_training_steps=num_training_steps, optimizer=optimizer)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 1118, in create_scheduler
    self.lr_scheduler = get_scheduler(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/optimization.py", line 388, in get_scheduler
    return schedule_func(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/optimization.py", line 174, in get_cosine_schedule_with_warmup
    return LambdaLR(optimizer, lr_lambda, last_epoch)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 217, in __init__
    super().__init__(optimizer, last_epoch, verbose)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 78, in __init__
    self._initial_step()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 84, in _initial_step
    self.step()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 147, in step
    values = self.get_lr()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 264, in get_lr
    return [base_lr * lmbda(self.last_epoch)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 264, in <listcomp>
    return [base_lr * lmbda(self.last_epoch)
TypeError: can't multiply sequence by non-int of type 'float'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1831058, ip=10.53.222.24, actor_id=3248fa26c35499a58d6bf00101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2e5a5bffa0>)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: can't multiply sequence by non-int of type 'float'
[2024-05-11 23:29:07,567][flwr][ERROR] - Traceback (most recent call last):
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1831058, ip=10.53.222.24, actor_id=3248fa26c35499a58d6bf00101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2e5a5bffa0>)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/scratch/nshaheen/project/may_federated/LLaVA_flowertune/client.py", line 84, in fit
    results = trainer.train()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 1638, in _inner_training_loop
    self.create_optimizer_and_scheduler(num_training_steps=max_steps)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 916, in create_optimizer_and_scheduler
    self.create_scheduler(num_training_steps=num_training_steps, optimizer=optimizer)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 1118, in create_scheduler
    self.lr_scheduler = get_scheduler(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/optimization.py", line 388, in get_scheduler
    return schedule_func(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/optimization.py", line 174, in get_cosine_schedule_with_warmup
    return LambdaLR(optimizer, lr_lambda, last_epoch)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 217, in __init__
    super().__init__(optimizer, last_epoch, verbose)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 78, in __init__
    self._initial_step()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 84, in _initial_step
    self.step()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 147, in step
    values = self.get_lr()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 264, in get_lr
    return [base_lr * lmbda(self.last_epoch)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 264, in <listcomp>
    return [base_lr * lmbda(self.last_epoch)
TypeError: can't multiply sequence by non-int of type 'float'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1831058, ip=10.53.222.24, actor_id=3248fa26c35499a58d6bf00101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2e5a5bffa0>)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: can't multiply sequence by non-int of type 'float'

[2024-05-11 23:29:07,569][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1831058, ip=10.53.222.24, actor_id=3248fa26c35499a58d6bf00101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2e5a5bffa0>)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/scratch/nshaheen/project/may_federated/LLaVA_flowertune/client.py", line 84, in fit
    results = trainer.train()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 1638, in _inner_training_loop
    self.create_optimizer_and_scheduler(num_training_steps=max_steps)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 916, in create_optimizer_and_scheduler
    self.create_scheduler(num_training_steps=num_training_steps, optimizer=optimizer)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/trainer.py", line 1118, in create_scheduler
    self.lr_scheduler = get_scheduler(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/optimization.py", line 388, in get_scheduler
    return schedule_func(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/transformers/optimization.py", line 174, in get_cosine_schedule_with_warmup
    return LambdaLR(optimizer, lr_lambda, last_epoch)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 217, in __init__
    super().__init__(optimizer, last_epoch, verbose)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 78, in __init__
    self._initial_step()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 84, in _initial_step
    self.step()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 147, in step
    values = self.get_lr()
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 264, in get_lr
    return [base_lr * lmbda(self.last_epoch)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 264, in <listcomp>
    return [base_lr * lmbda(self.last_epoch)
TypeError: can't multiply sequence by non-int of type 'float'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1831058, ip=10.53.222.24, actor_id=3248fa26c35499a58d6bf00101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2e5a5bffa0>)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: can't multiply sequence by non-int of type 'float'
[2024-05-11 23:29:07,570][flwr][INFO] - aggregate_fit: received 0 results and 2 failures
[2024-05-11 23:29:08,036][flwr][ERROR] - get_model() missing 2 required positional arguments: 'data_cfg' and 'tokenizer'
[2024-05-11 23:29:08,045][flwr][ERROR] - Traceback (most recent call last):
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/simulation/app.py", line 308, in start_simulation
    hist = run_fl(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/server/server.py", line 483, in run_fl
    hist, elapsed_time = server.fit(
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/server/server.py", line 126, in fit
    res_cen = self.strategy.evaluate(current_round, parameters=self.parameters)
  File "/home/nshaheen/anaconda3/envs/grad_proj/lib/python3.9/site-packages/flwr/server/strategy/fedavg.py", line 167, in evaluate
    eval_res = self.evaluate_fn(server_round, parameters_ndarrays, {})
  File "/scratch/nshaheen/project/may_federated/LLaVA_flowertune/utils.py", line 16, in evaluate
    model = get_model(model_cfg)
TypeError: get_model() missing 2 required positional arguments: 'data_cfg' and 'tokenizer'

[2024-05-11 23:29:08,047][flwr][ERROR] - Your simulation crashed :(. This could be because of several reasons. The most common are: 
	 > Sometimes, issues in the simulation code itself can cause crashes. It's always a good idea to double-check your code for any potential bugs or inconsistencies that might be contributing to the problem. For example: 
		 - You might be using a class attribute in your clients that hasn't been defined.
		 - There could be an incorrect method call to a 3rd party library (e.g., PyTorch).
		 - The return types of methods in your clients/strategies might be incorrect.
	 > Your system couldn't fit a single VirtualClient: try lowering `client_resources`.
	 > All the actors in your pool crashed. This could be because: 
		 - You clients hit an out-of-memory (OOM) error and actors couldn't recover from it. Try launching your simulation with more generous `client_resources` setting (i.e. it seems {'num_cpus': 2, 'num_gpus': 1.0} is not enough for your run). Use fewer concurrent actors. 
		 - You were running a multi-node simulation and all worker nodes disconnected. The head node might still be alive but cannot accommodate any actor with resources: {'num_cpus': 2, 'num_gpus': 1.0}.
Take a look at the Flower simulation examples for guidance <https://flower.ai/docs/framework/how-to-run-simulations.html>.
